'use strict';

const Types = {
  SAVE_USER_DATA: 'SAVE_USER_DATA',
  UPDATE_USER_DATA: 'UPDATE_USER_DATA',
  CLEAR_USER_DATA: 'CLEAR_USER_DATA',
  CLEAR_USER_AUTH: 'CLEAR_USER_AUTH',
  CLEAR_USER_SESSION: 'CLEAR_USER_SESSION',

  SET_LOADING: 'SET_LOADING',
  SET_LANGUAGE: 'SET_LANGUAGE',

  UPDATE_REGISTRATION_DATA: 'UPDATE_REGISTRATION_DATA',
  CLEAR_REGISTRATION_DATA: 'CLEAR_REGISTRATION_DATA',
  RESET_PASSCODE: 'RESET_PASSCODE',
  CACHE_PHONE_NUMBER: 'CACHE_PHONE_NUMBER',

  REQUEST_USER_BALANCE: 'REQUEST_USER_BALANCE',
  RECEIVED_USER_BALANCE: 'RECEIVED_USER_BALANCE',

  REQUEST_BADGE_STATUS: 'REQUEST_BADGE_STATUS',
  RECEIVED_BADGE_STATUS: 'RECEIVED_BADGE_STATUS',

  REQUEST_GET_PROFILE: 'REQUEST_GET_PROFILE',
  RECEIVED_GET_PROFILE: 'RECEIVED_GET_PROFILE',

  SHOW_UPDATE_MODAL: 'SHOW_UPDATE_MODAL',

  REQUEST_GET_ACCOUNTS: 'REQUEST_GET_ACCOUNTS',
  RECEIVED_GET_ACCOUNTS: 'RECEIVED_GET_ACCOUNTS',

  REQUEST_GET_DEFAULT_ACCOUNTS: 'REQUEST_GET_DEFAULT_ACCOUNTS',
  RECEIVED_GET_DEFAULT_ACCOUNTS: 'RECEIVED_GET_DEFAULT_ACCOUNTS'
};

export default Types;
