/**
 * Event names for Device Event Emitter.
 */

export const Events = {
  RELOAD_PHONE_NUMBER: 'RELOAD_PHONE_NUMBER',
  DRAWER_TOGGLE: 'DRAWER_TOGGLE',
  DRAWER_CLOSE: 'DRAWER_CLOSE',
  CHECK_NOTIFICATIONS: 'CHECK_NOTIFICATIONS',
  UPDATE_NOTIFICATION: 'UPDATE_NOTIFICATION',
  NEXT_STEP_RESULT: 'NEXT_STEP_RESULT'
};
