version: '3.3'
services:
  trip-contract-operators:
    #logging:
    #  driver: awslogs
    #  options:
    #    awslogs-region: ap-northeast-1
    #    awslogs-group: trip-contract-operators
    #    awslogs-create-group: 'true'
    #    awslogs-multiline-pattern: '(INFO|DEBUG|ERROR|WARNNING)'
    build:
      context: ./
    environment:
      - LOG_LEVEL=info
    ports:
      - 3000:3000
    restart: always